/*
2 *ThisJava source file was generated bythe Gradle'init'task.
3 */
package basic_demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest= new App();
        assertNotNull("app should have agreeting",classUnderTest.getGreeting());
    }
}